"""DuckDB-backed session storage for Module 2."""

from .duckdb_compat import DuckDBConnection, duckdb_connect
from .session_db import (
    get_session_db,
    get_session_lock,
    close_session_db,
    delete_session_db,
    safe_table_name,
    register_table,
    unregister_table,
    lookup_sql_name,
    all_registered_tables,
    cleanup_stale_sessions,
    cleanup_all_sessions,
    DB_DIR,
)
from .meta_ops import get_meta, set_meta, delete_meta, get_all_meta_keys
from .table_ops import (
    store_table,
    store_table_streaming,
    store_df_native,
    read_table,
    read_table_columns,
    table_exists,
    drop_table,
    table_row_count,
    iterate_table,
    quote_id,
)
from .bridge import sqlite_to_df, df_to_sqlite, PREVIEW_POOL, pick_best_rows, pick_best_df_rows

__all__ = [
    "DuckDBConnection",
    "duckdb_connect",
    "get_session_db",
    "get_session_lock",
    "close_session_db",
    "delete_session_db",
    "safe_table_name",
    "register_table",
    "unregister_table",
    "lookup_sql_name",
    "all_registered_tables",
    "cleanup_stale_sessions",
    "cleanup_all_sessions",
    "DB_DIR",
    "get_meta",
    "set_meta",
    "delete_meta",
    "get_all_meta_keys",
    "store_table",
    "store_table_streaming",
    "store_df_native",
    "read_table",
    "read_table_columns",
    "table_exists",
    "drop_table",
    "table_row_count",
    "iterate_table",
    "quote_id",
    "sqlite_to_df",
    "df_to_sqlite",
    "PREVIEW_POOL",
    "pick_best_rows",
    "pick_best_df_rows",
]
