"""Shared database utilities for on-disk DuckDB session management."""

from .duckdb_compat import DuckDBConnection, duckdb_connect
from .session_db import (
    get_session_db,
    get_session_lock,
    close_session_db,
    delete_session_db,
    safe_table_name,
    register_table,
    unregister_table,
    lookup_sql_name,
    all_registered_tables,
    cleanup_stale_sessions,
    cleanup_all_sessions,
    DB_DIR,
)
from .meta_ops import get_meta, set_meta, delete_meta, get_all_meta_keys
from .table_ops import (
    store_table,
    store_table_streaming,
    store_df_native,
    read_table,
    read_table_columns,
    table_exists,
    drop_table,
    table_row_count,
    iterate_table,
    quote_id,
    normalize_for_match,
    PREVIEW_POOL,
    pick_best_rows,
    pick_best_raw_rows,
)
from .stats_ops import (
    column_stats,
    column_distinct_values,
    column_distinct_count,
    column_null_count,
    compute_overlap,
    distinct_values_by_column_sql,
    get_overlap_sql,
)

__all__ = [
    "DuckDBConnection",
    "duckdb_connect",
    "get_session_db",
    "get_session_lock",
    "close_session_db",
    "delete_session_db",
    "safe_table_name",
    "register_table",
    "unregister_table",
    "lookup_sql_name",
    "all_registered_tables",
    "cleanup_stale_sessions",
    "cleanup_all_sessions",
    "DB_DIR",
    "get_meta",
    "set_meta",
    "delete_meta",
    "get_all_meta_keys",
    "store_table",
    "store_table_streaming",
    "store_df_native",
    "read_table",
    "read_table_columns",
    "table_exists",
    "drop_table",
    "table_row_count",
    "iterate_table",
    "quote_id",
    "normalize_for_match",
    "column_stats",
    "column_distinct_values",
    "column_distinct_count",
    "column_null_count",
    "compute_overlap",
    "distinct_values_by_column_sql",
    "get_overlap_sql",
    "PREVIEW_POOL",
    "pick_best_rows",
    "pick_best_raw_rows",
]
